remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: SymClosestWannier
description: A Python library to create Symmetry-adapted Closest Wannier (SymCW) tight-binding model based on Symmetry-Adapted Multipole Basis (SAMB) and Plane-Wave (PW) DFT calculation.
